spring:
  application:
    name: ticket-app

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ticket_app}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      database: 0
      host: ${REDIS_HOST:localhost}
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: abdufattoxovshaxzod0404@gmail.com
    password: mksc hvnb oagh dvzb
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 9090

file:
  storage:
    path: C:\Users\smart\OneDrive\Desktop\ticket-app files\storage
  access:
    url: http://149.102.137.239:8080/api/v1/files/
    compressedUrl: http://149.102.137.239:8080/api/v1/files/compressed/

#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE
#    org.hibernate.engine.transaction.internal.TransactionImpl: DEBUG

app:
  mail:
    from: "Ticket App <no-reply@ticketapp.com>"

ticket:
  base-url: http://localhost:9090

