spring:
  application:
    name: ticket-app

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ticket_app}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      database: 0
      host: ${REDIS_HOST:localhost}
      port: 6379

server:
  port: 9090

file:
  storage:
    path: C:\Users\smart\OneDrive\Desktop\ticket-app files\storage
  access:
    url: http://149.102.137.239:8080/api/v1/files/
    compressedUrl: http://149.102.137.239:8080/api/v1/files/compressed/

